# a different set of attributes
services:
  parsedmarc:
    build: ./parsedmarc/
    volumes:
      - parsedmarc_input:/input:ro
      - parsedmarc_output_files:/output
    command: parsedmarc -c /parsedmarc.ini /input/* --debug
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.transport.ssl.verification_mode=certificate
      - cluster.name=parsedmarc
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: [ "CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - parsedmarc_elastic_data:/usr/share/elasticsearch/data

  grafana:
    build: ./grafana/
    ports:
      - 3000:3000
    user: root
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
      GF_AUTH_ANONYMOUS_ENABLED: 'true'

volumes:
  parsedmarc_input:
  parsedmarc_output_files:
  parsedmarc_elastic_data: